version : "3"
services:
  laravel-gcp-api:
    build:
      context: .
      dockerfile: dockerfiles/Ci.Dockerfile
    container_name: laravel-gcp-api
    depends_on:
      - laravel-gcp-pg
    restart: always
    ports:
      - "1818:80"
    environment:
      APP_NAME: "Laravel API boilerplate"
      DB_HOST: "laravel-gcp-pg"
      MAIL_HOST: "laravel-gcp-mailpit"
    networks:
      laravel-gcp-network:
        ipv4_address: 18.18.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  laravel-gcp-pg:
    image: postgres:15
    container_name: laravel-gcp-pg
    volumes:
      - laravel-gcp-pg-disk:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      laravel-gcp-network:
        ipv4_address: 18.18.1.2

  laravel-gcp-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: laravel-gcp-mailpit
    restart: always
    networks:
      laravel-gcp-network:
        ipv4_address: 18.18.1.3

#  laravel-gcp-q:
#    build:
#      context: .
#      dockerfile: dockerfiles/QueueListener.Dockerfile
#    container_name: laravel-gcp-q
#    depends_on:
#      - laravel-gcp-api
#    volumes:
#      - .:/var/www/html
#    restart: unless-stopped
#    networks:
#      laravel-gcp-network:
#        ipv4_address: 10.10.1.4

#  laravel-gcp-0x:
#    build:
#      context: .
#      dockerfile: dockerfiles/0x.Dockerfile
#    container_name: laravel-gcp-0x
#    depends_on:
#      - laravel-gcp-api
#    volumes:
#      - .:/var/www/html
#    restart: always
#    networks:
#      laravel-gcp-network:
#        ipv4_address: 10.10.1.5

#  laravel-gcp-fe-app:
#    build:
#      context: .
#      dockerfile: dockerfiles/FeApp.Dockerfile
#    container_name: laravel-gcp-fe-app
#    ports:
#      - "1001:3000"
#    volumes:
#      - ./fe-app:/var/www/html
#      #- ./dockerfiles:/var/www/html/dockerfiles
#    restart: always
#    networks:
#      laravel-gcp-network:
#        ipv4_address: 10.10.1.6

# On-disk storage of DB data, when containers are stopped
volumes:
  laravel-gcp-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  laravel-gcp-network:
    ipam:
      driver: default
      config:
        - subnet: 18.18.0.0/16
