version : "3"
services:
  ci-lbp-api:
    build:
      context: .
      dockerfile: dockerfiles/Ci.Dockerfile
    container_name: ci-lbp-api
    depends_on:
      - ci-lbp-pg
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "1010:80"
    environment:
      APP_NAME: "Laravel API boilerplate"
      DB_HOST: "ci-lbp-pg"
      MAIL_HOST: "ci-lbp-mailpit"
    networks:
      ci-lbp-network:
        ipv4_address: 10.10.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  ci-lbp-pg:
    image: postgres:15
    container_name: ci-lbp-pg
    volumes:
      - ci-lbp-pg-disk:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      ci-lbp-network:
        ipv4_address: 10.10.1.2

  ci-lbp-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: ci-lbp-mailpit
    restart: always
    networks:
      lbp-network:
        ipv4_address: 10.10.1.3

#  lbp-q:
#    build:
#      context: .
#      dockerfile: dockerfiles/QueueListener.Dockerfile
#    container_name: lbp-q
#    depends_on:
#      - lbp-api
#    volumes:
#      - .:/var/www/html
#    restart: unless-stopped
#    networks:
#      lbp-network:
#        ipv4_address: 10.10.1.4

#  lbp-0x:
#    build:
#      context: .
#      dockerfile: dockerfiles/0x.Dockerfile
#    container_name: lbp-0x
#    depends_on:
#      - lbp-api
#    volumes:
#      - .:/var/www/html
#    restart: always
#    networks:
#      lbp-network:
#        ipv4_address: 10.10.1.5

#  lbp-fe-app:
#    build:
#      context: .
#      dockerfile: dockerfiles/FeApp.Dockerfile
#    container_name: lbp-fe-app
#    ports:
#      - "1001:3000"
#    volumes:
#      - ./fe-app:/var/www/html
#      #- ./dockerfiles:/var/www/html/dockerfiles
#    restart: always
#    networks:
#      lbp-network:
#        ipv4_address: 10.10.1.6

# On-disk storage of DB data, when containers are stopped
volumes:
  ci-lbp-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  ci-lbp-network:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
