version : "3"
services:
  laravel-gcp-api:
    build:
      context: .
      dockerfile: dockerfiles/Api.Dockerfile
    container_name: laravel-gcp-api
    depends_on:
      - laravel-gcp-pg
#      - laravel-gcp-es
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "1818:80"
    networks:
      laravel-gcp-network:
        ipv4_address: 18.18.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  laravel-gcp-pg:
    image: postgres:15
    container_name: laravel-gcp-pg
    volumes:
      - laravel-gcp-pg-disk:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    ports:
      - "5444:5432"
    networks:
      laravel-gcp-network:
        ipv4_address: 18.18.1.2

  laravel-gcp-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: laravel-gcp-mailpit
    restart: always
    ports:
      - "1828:8025"
    networks:
      laravel-gcp-network:
        ipv4_address: 18.18.1.3

  laravel-gcp-q:
    build:
      context: .
      dockerfile: dockerfiles/QueueListener.Dockerfile
    container_name: laravel-gcp-q
    depends_on:
      - laravel-gcp-api
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      laravel-gcp-network:
        ipv4_address: 18.18.1.4

#  laravel-gcp-es:
#    image: elasticsearch:7.17.12
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    volumes:
#      - laravel-gcp-elasticsearch-disk:/usr/share/elasticsearch/data
#    networks:
#      laravel-gcp-network:
#        ipv4_address: 10.10.1.7

#  laravel-gcp-0x:
#    build:
#      context: .
#      dockerfile: dockerfiles/0x.Dockerfile
#    container_name: laravel-gcp-0x
#    depends_on:
#      - laravel-gcp-api
#    volumes:
#      - .:/var/www/html
#    restart: always
#    networks:
#      laravel-gcp-network:
#        ipv4_address: 10.10.1.5

#  laravel-gcp-fe-app:
#    build:
#      context: .
#      dockerfile: dockerfiles/FeApp.Dockerfile
#    container_name: laravel-gcp-fe-app
#    ports:
#      - "1001:3000"
#    volumes:
#      - ./fe-app:/var/www/html
#      #- ./dockerfiles:/var/www/html/dockerfiles
#    restart: always
#    networks:
#      laravel-gcp-network:
#        ipv4_address: 10.10.1.6

# On-disk storage of DB data, when containers are stopped
volumes:
  laravel-gcp-pg-disk: {}
  laravel-gcp-elasticsearch-disk:
    driver: local

# Local network for services running using this docker-compose config
networks:
  laravel-gcp-network:
    ipam:
      driver: default
      config:
        - subnet: 18.18.0.0/16
