name: CI

on:
  push:
    paths:
      - '**/.php'
      - '.env.*'
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose
        run: docker-compose up -d

      - name: Composer install
        run: docker-compose exec -T lbp-0x composer install

      - name: CI checks
        run: docker-compose exec -T lbp-0x composer run ci
